import { useState } from "react";
import Header from "@/components/Header";
import SectionDisplay from "@/components/SectionDisplay";
import ChatPanel from "@/components/ChatPanel";
import LoadingState from "@/components/LoadingState";
import { ArrowRight, Upload } from "lucide-react";

const CRITIQUE_SECTIONS = [
  { key: "overall_assessment", label: "Overall Assessment" },
  { key: "strengths", label: "Strengths" },
  { key: "gaps_and_blind_spots", label: "Gaps & Blind Spots" },
  { key: "framework_alignment", label: "Framework Alignment" },
  { key: "suggested_improvements", label: "Suggested Improvements" },
  { key: "lennys_lens", label: "Lenny's Lens" },
];

const LOADING_MESSAGES = [
  "Reading your teardown...",
  "Identifying gaps...",
  "Applying frameworks...",
  "Writing your critique...",
];

interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
}

const Critique = () => {
  const [activeTab, setActiveTab] = useState<"write" | "upload">("write");
  const [teardownText, setTeardownText] = useState("");
  const [productName, setProductName] = useState("");
  const [fileName, setFileName] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [critique, setCritique] = useState<Record<string, string> | null>(null);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = (ev) => {
      setTeardownText(ev.target?.result as string);
    };
    reader.readAsText(file);
  };

  const handleCritique = async () => {
    if (!teardownText.trim()) return;
    setIsLoading(true);
    setTimeout(() => {
      const mock: Record<string, string> = {};
      CRITIQUE_SECTIONS.forEach((s) => {
        mock[s.key] = `This is the ${s.label.toLowerCase()} of your teardown${productName ? ` for ${productName}` : ""}. In the full implementation, this would contain 2-4 paragraphs of specific, constructive critique generated by AI, addressing what you did well and where you can improve.`;
      });
      setCritique(mock);
      setIsLoading(false);
    }, 3000);
  };

  const handleChatSend = (message: string) => {
    const userMsg: ChatMessage = { id: Date.now().toString(), role: "user", content: message };
    setChatMessages((prev) => [...prev, userMsg]);
    setTimeout(() => {
      const assistantMsg: ChatMessage = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: "This is a placeholder response. In the full implementation, this would be a context-aware answer referencing your critique.",
      };
      setChatMessages((prev) => [...prev, assistantMsg]);
    }, 1000);
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="max-w-[860px] mx-auto px-6 py-12">
        {!critique && !isLoading && (
          <div className="py-8">
            <div className="flex gap-6 mb-8 border-b border-border">
              <button
                onClick={() => setActiveTab("write")}
                className={`pb-3 text-sm font-body transition-colors border-b-2 -mb-px ${
                  activeTab === "write"
                    ? "border-primary text-foreground"
                    : "border-transparent text-muted-foreground hover:text-foreground"
                }`}
              >
                Write
              </button>
              <button
                onClick={() => setActiveTab("upload")}
                className={`pb-3 text-sm font-body transition-colors border-b-2 -mb-px ${
                  activeTab === "upload"
                    ? "border-primary text-foreground"
                    : "border-transparent text-muted-foreground hover:text-foreground"
                }`}
              >
                Upload
              </button>
            </div>

            {activeTab === "write" ? (
              <textarea
                value={teardownText}
                onChange={(e) => setTeardownText(e.target.value)}
                placeholder="Write or paste your teardown here..."
                className="w-full h-64 bg-transparent border border-border focus:border-primary outline-none p-4 text-sm font-mono text-foreground placeholder:text-muted-foreground/50 resize-none transition-colors"
              />
            ) : (
              <label className="block border border-dashed border-border hover:border-primary p-12 text-center cursor-pointer transition-colors">
                <input
                  type="file"
                  accept=".pdf,.docx,.txt"
                  onChange={handleFileUpload}
                  className="hidden"
                />
                {fileName ? (
                  <p className="font-mono text-sm text-foreground">{fileName}</p>
                ) : (
                  <div>
                    <Upload className="w-5 h-5 text-muted-foreground mx-auto mb-3" />
                    <p className="font-body text-sm text-muted-foreground">
                      Drop a file or click to upload
                    </p>
                    <p className="font-mono text-xs text-muted-foreground/50 mt-1">
                      .pdf, .docx, .txt
                    </p>
                  </div>
                )}
              </label>
            )}

            <div className="mt-6">
              <input
                type="text"
                value={productName}
                onChange={(e) => setProductName(e.target.value)}
                placeholder="What product is this a teardown of? (optional)"
                className="w-full bg-transparent border-b border-border focus:border-primary outline-none py-3 text-sm font-body text-foreground placeholder:text-muted-foreground/50 transition-colors"
              />
            </div>

            <button
              onClick={handleCritique}
              disabled={!teardownText.trim()}
              className="mt-8 inline-flex items-center gap-2 bg-primary text-primary-foreground px-6 py-3 text-sm font-body font-medium hover:opacity-90 disabled:opacity-30 transition-opacity"
            >
              Get Critique
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        )}

        {isLoading && <LoadingState messages={LOADING_MESSAGES} />}

        {critique && !isLoading && (
          <div>
            <h1 className="font-heading text-4xl md:text-5xl font-semibold text-foreground mb-2">
              Critique
            </h1>
            {productName && (
              <p className="font-mono text-sm text-muted-foreground mb-10">{productName}</p>
            )}
            <SectionDisplay
              sections={CRITIQUE_SECTIONS.map((s) => ({
                key: s.key,
                label: s.label,
                content: critique[s.key] || "",
              }))}
            />
            <ChatPanel messages={chatMessages} onSend={handleChatSend} />
          </div>
        )}
      </main>
    </div>
  );
};

export default Critique;
