import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import AppLayout from "@/components/AppLayout";
import SectionDisplay from "@/components/SectionDisplay";
import ChatPanel from "@/components/ChatPanel";
import LoadingState from "@/components/LoadingState";
import DownloadButton from "@/components/DownloadButton";
import { ArrowRight } from "lucide-react";
import { saveEntry, getEntry } from "@/lib/history";

const GENERATE_SECTIONS = [
  { key: "product_overview", label: "Product Overview" },
  { key: "strategy_and_positioning", label: "Strategy & Positioning" },
  { key: "feature_breakdown", label: "Feature Breakdown" },
  { key: "growth_model", label: "Growth Model" },
  { key: "design_analysis", label: "Design Analysis" },
  { key: "key_insights", label: "Key Insights" },
  { key: "lennys_lens", label: "Lenny's Lens" },
];

const LOADING_MESSAGES = [
  "Analyzing product strategy...",
  "Reviewing growth model...",
  "Synthesizing design patterns...",
  "Applying frameworks...",
];

interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
}

const Generate = () => {
  const { id } = useParams<{ id?: string }>();
  const [productName, setProductName] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [teardown, setTeardown] = useState<Record<string, string> | null>(null);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [entryId, setEntryId] = useState<string>("");

  // Load existing entry if navigating from history
  useEffect(() => {
    if (id) {
      const entry = getEntry(id);
      if (entry) {
        setProductName(entry.product_name);
        const sectionMap: Record<string, string> = {};
        entry.sections.forEach((s) => { sectionMap[s.key] = s.content; });
        setTeardown(sectionMap);
        setChatMessages(entry.chatMessages);
        setEntryId(entry.id);
      }
    }
  }, [id]);

  const handleGenerate = async () => {
    if (!productName.trim()) return;
    setIsLoading(true);
    setTimeout(() => {
      const mock: Record<string, string> = {};
      GENERATE_SECTIONS.forEach((s) => {
        if (s.key === "lennys_lens") {
          mock[s.key] = `Lenny's take, drawing on conversations with Elena Verna and Casey Winters: ${productName} represents a masterclass in product-led growth. The core insight — validated across dozens of conversations on the podcast — is that the best products don't just solve a problem, they create a new habit loop. ${productName} does this by embedding itself into existing workflows rather than asking users to adopt new ones.`;
        } else {
          mock[s.key] = `This is the ${s.label.toLowerCase()} analysis for ${productName}. In a full implementation, this would contain 2-4 paragraphs of substantive, specific analysis generated by AI. (Elena Verna, Growth) The teardown would cover strategic positioning, competitive dynamics, and unique insights about how ${productName} operates in its market. (Shreyas Doshi, Product Strategy) Each section draws on frameworks and mental models from the best product thinkers, attributed inline to specific experts.`;
        }
      });
      setTeardown(mock);
      setIsLoading(false);

      // Save to history
      const newId = Date.now().toString();
      setEntryId(newId);
      const sections = GENERATE_SECTIONS.map((s) => ({ key: s.key, label: s.label, content: mock[s.key] || "" }));
      saveEntry({
        id: newId,
        product_name: productName,
        mode: "generate",
        created_at: new Date().toISOString(),
        sections,
        chatMessages: [],
      });
    }, 3000);
  };

  const handleChatSend = (message: string) => {
    const userMsg: ChatMessage = { id: Date.now().toString(), role: "user", content: message };
    const newMessages = [...chatMessages, userMsg];
    setChatMessages(newMessages);
    setTimeout(() => {
      const assistantMsg: ChatMessage = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: "This is a placeholder response. In the full implementation, this would be a context-aware answer using the teardown as reference.",
      };
      const updatedMessages = [...newMessages, assistantMsg];
      setChatMessages(updatedMessages);
      // Update history with chat
      if (entryId && teardown) {
        const sections = GENERATE_SECTIONS.map((s) => ({ key: s.key, label: s.label, content: teardown[s.key] || "" }));
        saveEntry({
          id: entryId,
          product_name: productName,
          mode: "generate",
          created_at: new Date().toISOString(),
          sections,
          chatMessages: updatedMessages,
        });
      }
    }, 1000);
  };

  const sections = teardown
    ? GENERATE_SECTIONS.map((s) => ({ key: s.key, label: s.label, content: teardown[s.key] || "" }))
    : [];

  return (
    <AppLayout>
      <div className="max-w-[860px] mx-auto px-6 py-12">
        {!teardown && !isLoading && (
          <div className="py-16">
            <label className="block font-mono text-xs uppercase tracking-[0.15em] text-muted-foreground mb-6">
              What product do you want to tear down?
            </label>
            <input
              type="text"
              value={productName}
              onChange={(e) => setProductName(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
              placeholder="e.g. Plaid, Duolingo, Figma's multiplayer feature..."
              className="w-full bg-transparent border-b border-border focus:border-primary outline-none py-3 text-xl font-body text-foreground placeholder:text-muted-foreground/50 transition-colors"
            />
            <button
              onClick={handleGenerate}
              disabled={!productName.trim()}
              className="mt-8 inline-flex items-center gap-2 bg-primary text-primary-foreground px-6 py-3 text-sm font-body font-medium hover:opacity-90 disabled:opacity-30 transition-opacity"
            >
              Generate Teardown
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        )}

        {isLoading && <LoadingState messages={LOADING_MESSAGES} />}

        {teardown && !isLoading && (
          <div>
            <div className="flex items-start justify-between mb-10">
              <h1 className="font-heading text-4xl md:text-5xl font-semibold text-foreground">
                {productName}
              </h1>
              <DownloadButton productName={productName} sections={sections} />
            </div>
            <SectionDisplay sections={sections} />
            <ChatPanel messages={chatMessages} onSend={handleChatSend} />
          </div>
        )}
      </div>
    </AppLayout>
  );
};

export default Generate;
