import { useState } from "react";
import Header from "@/components/Header";
import SectionDisplay from "@/components/SectionDisplay";
import ChatPanel from "@/components/ChatPanel";
import LoadingState from "@/components/LoadingState";
import { ArrowRight } from "lucide-react";

const GENERATE_SECTIONS = [
  { key: "product_overview", label: "Product Overview" },
  { key: "strategy_and_positioning", label: "Strategy & Positioning" },
  { key: "feature_breakdown", label: "Feature Breakdown" },
  { key: "growth_model", label: "Growth Model" },
  { key: "design_analysis", label: "Design Analysis" },
  { key: "key_insights", label: "Key Insights" },
  { key: "lennys_lens", label: "Lenny's Lens" },
];

const LOADING_MESSAGES = [
  "Analyzing product strategy...",
  "Reviewing growth model...",
  "Synthesizing design patterns...",
  "Applying frameworks...",
];

interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
}

const Generate = () => {
  const [productName, setProductName] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [teardown, setTeardown] = useState<Record<string, string> | null>(null);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);

  const handleGenerate = async () => {
    if (!productName.trim()) return;
    setIsLoading(true);
    // TODO: Call AI API
    // Simulating for now
    setTimeout(() => {
      const mock: Record<string, string> = {};
      GENERATE_SECTIONS.forEach((s) => {
        mock[s.key] = `This is the ${s.label.toLowerCase()} analysis for ${productName}. In a full implementation, this would contain 2-4 paragraphs of substantive, specific analysis generated by AI. The teardown would cover strategic positioning, competitive dynamics, and unique insights about how ${productName} operates in its market.`;
      });
      setTeardown(mock);
      setIsLoading(false);
    }, 3000);
  };

  const handleChatSend = (message: string) => {
    const userMsg: ChatMessage = { id: Date.now().toString(), role: "user", content: message };
    setChatMessages((prev) => [...prev, userMsg]);
    // TODO: Call AI chat API
    setTimeout(() => {
      const assistantMsg: ChatMessage = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: "This is a placeholder response. In the full implementation, this would be a context-aware answer using the teardown as reference.",
      };
      setChatMessages((prev) => [...prev, assistantMsg]);
    }, 1000);
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="max-w-[860px] mx-auto px-6 py-12">
        {!teardown && !isLoading && (
          <div className="py-16">
            <label className="block font-mono text-xs uppercase tracking-[0.15em] text-muted-foreground mb-6">
              What product do you want to tear down?
            </label>
            <input
              type="text"
              value={productName}
              onChange={(e) => setProductName(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
              placeholder="e.g. Plaid, Duolingo, Figma's multiplayer feature..."
              className="w-full bg-transparent border-b border-border focus:border-primary outline-none py-3 text-xl font-body text-foreground placeholder:text-muted-foreground/50 transition-colors"
            />
            <button
              onClick={handleGenerate}
              disabled={!productName.trim()}
              className="mt-8 inline-flex items-center gap-2 bg-primary text-primary-foreground px-6 py-3 text-sm font-body font-medium hover:opacity-90 disabled:opacity-30 transition-opacity"
            >
              Generate Teardown
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        )}

        {isLoading && <LoadingState messages={LOADING_MESSAGES} />}

        {teardown && !isLoading && (
          <div>
            <h1 className="font-heading text-4xl md:text-5xl font-semibold text-foreground mb-10">
              {productName}
            </h1>
            <SectionDisplay
              sections={GENERATE_SECTIONS.map((s) => ({
                key: s.key,
                label: s.label,
                content: teardown[s.key] || "",
              }))}
            />
            <ChatPanel
              messages={chatMessages}
              onSend={handleChatSend}
            />
          </div>
        )}
      </main>
    </div>
  );
};

export default Generate;
